export const WARD_LIST = [
    "An Khánh", "Bất Bạt", "Ba Đình", "Bình Minh", "Bạch Mai",
    "Bồ Đề", "Bát Tràng", "Ba Vì", "Chương Dương", "Cầu Giấy",
    "Chương Mỹ", "Cửa Nam", "Cổ Đô", "Chuyên Mỹ", "Đông Anh",
    "Định Công", "Đống Đa", "Đa Phúc", "Đoài Phương", "Dân Hòa",
    "Dương Nội", "Đông Ngạc", "Đại Mỗ", "Đan Phượng", "Đại Thanh",
    "Dịch Vọng", "Dịch Vọng Hậu",
    "Dương Hòa", "Đại Xuyên", "Phúc Thọ", "Gia Lâm", "Giảng Võ",
    "Hát Môn", "Hạ Bằng", "Hà Đông", "Hồng Hà", "Hoàng Liệt",
    "Hoàn Kiếm", "Hòa Lạc", "Hoàng Mai", "Hồng Sơn", "Hưng Đạo",
    "Hòa Phú", "Hương Sơn", "Hai Bà Trưng", "Hoài Đức", "Hồng Vân",
    "Hòa Xá", "Kim Anh", "Khương Đình", "Kiến Hưng", "Kim Liên",
    "Kiều Phú", "Láng", "Long Biên", "Liên Minh", "Lĩnh Nam",
    "Minh Châu", "Mỹ Đức", "Mê Linh", "Ngọc Hà", "Nội Bài",
    "Nghĩa Đô", "Ngọc Hồi", "Nam Phù", "Ô Chợ Dừa", "Ô Diên",
    "Phú Cát", "Phù Đổng", "Phú Diễn", "Phú Lương", "Phúc Thịnh",
    "Phúc Lợi", "Phương Liệt", "Phú Nghĩa", "Phúc Lộc", "Phúc Sơn",
    "Phú Thượng", "Phượng Dực", "Phú Xuyên", "Quảng Oai", "Quảng Bị",
    "Quang Minh", "Quốc Oai", "Sơn Đồng", "Suối Hai", "Sóc Sơn",
    "Sơn Tây", "Thuận An", "Tùng Thiện", "Thượng Cát", "Thiên Lộc",
    "Từ Liêm", "Tây Phương", "Tiến Thắng", "Tây Hồ", "Thanh Liệt",
    "Thượng Phúc", "Thư Lâm", "Tương Mai", "Tam Hưng", "Thanh Oai",
    "Trần Phú", "Trung Giã", "Thạch Thất", "Thanh Trì", "Thường Tín",
    "Tây Tựu", "Thanh Xuân", "Tây Mỗ", "Ứng Hòa", "Ứng Thiên",
    "Vĩnh Thanh", "Vân Đình", "Vĩnh Hưng", "Việt Hưng", "Vật Lại",
    "Văn Miếu - Quốc Tử Giám", "Vĩnh Tuy", "Xuân Đỉnh", "Xuân Mai",
    "Xuân Phương", "Yên Bài", "Yên Hòa", "Yên Lãng", "Yên Nghĩa",
    "Yên Sở", "Yên Xuân"
].sort((a, b) => a.localeCompare(b, 'vi'));
